[package]
name = "nave"
version = "0.1.0"
edition = "2021"

[dependencies]
fastnoise-lite = "1.1.1"
image = "0.25.5"
minifb = "0.27.0"
nalgebra-glm = "0.19.0"
once_cell = "1.20.2"
rand = "0.8.5"
tobj = "4.0.2"
